### ISSUE TITLE
figure3a.ttl: Should we represent latitude and longitude using a standard geo vocabulary?

### ISSUE THREAD

**Issue by lschmelzeisen** [knowledge-graphs-tutorial/examples#4]
Currently, we use our own `:lat` and `:long` relation to encode latitude and logitude:

https://github.com/knowledge-graphs-tutorial/examples/blob/37cc7fda85450d9caec87a946acac98d46e74b5b/Section2/2_1_3_Property_graphs/figure3a.ttl#L21-L27

We could switch to to using the standardized [Basic Geo (WGS84 lat/long) Vocabulary](https://www.w3.org/2003/01/geo/).

Should we do this to showcase how different vocabularies can be incorporated into RDF, or would it make the example code needlessly complicated? Would there be a better vocabulary to use?

**Comment by aidhog** [comment]
I think that José had also just used `:term` throughout in the original examples. I changed to use `rdf:type` but nothing more. 

My conclusion was that if we try to reuse vocabularies for fixed examples, then often the vocabularies will not model data precisely the same way as the example, or may use slightly different term names. Then it becomes tricky to say how far we can deviate from the example in order to follow a vocabulary. Another option would be to change the examples to fit the vocabulary, but the goal of the examples I think is clarity and conciseness, and trying to follow real vocabularies might not always be compatible with that goal. 

Maybe we could rather add comments to the examples to suggest real vocabularies that could be used in practice.

**Comment by lschmelzeisen** [comment]
Yes, seems sensible.
